### ISSUE TITLE
Feat request: improve dom of tree node

### ISSUE THREAD

**Issue by aixfox** [react-component/tree#198]
Hi,

现在的树节点有点不合理的地方。

https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L528
```javascript
      <li>
        {this.renderSwitcher()}
        {this.renderCheckbox()}
        {this.renderSelector()}
        {this.renderChildren()}
      </li>
```

其中 switcher checkbox selector 应该属于这个节点的 title，下方的 children 属于 children，dom 结构上似乎应该区分开。好处是方便对节点的 title 做处理。

比如选择节点的整行背景色，以及扩展点击区域至整行
![default](https://user-images.githubusercontent.com/28643426/47401528-5fe7b900-d774-11e8-9bf0-702d88127942.png)

dom 结构
![default](https://user-images.githubusercontent.com/28643426/47401625-b48b3400-d774-11e8-8331-b227968b900e.png)

目前的实现方式
```scss
.ant-tree {
  float: left;  // 撑开右侧超出父容器100%的宽度，撑开右侧背景色
  min-width: 100%;

  .ant-tree-node-content-wrapper {
    width: calc(100% - 30px);  // 计算 switcher checkbox 剩下的宽度

    .ant-tree-title {
      display: block;
      width: 100%;

      // 撑开左侧背景色
      margin-left: -9999px;
      padding-left: 9999px;
    }
  }
}
```

这样就显得十分的别扭，如果有一个 .ant-tree-node-title 的话，就可以 width 100% 然后撑开左侧，而不是去找一个合适的后代假装是那个节点。

因为涉及到 dom 的变更，可能会带来兼容问题，没有直接 pr。后续可否考虑一下？
